/**
 * Copyright 2014 ginstr GmbH
 * 
 * This work is licensed under the Creative Commons Attribution-NonCommercial 4.0 International License.
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/ 
 *  
 *  Unless required by applicable law or agreed to in writing, software 
 *  distributed under the License is distributed on an "AS IS" BASIS, 
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 *  See the License for the specific language governing permissions and 
 *  limitations under the License. 
 */
package com.enaikoon.android.service.baseservice;

import android.content.Intent;

/**
 * A wrapper to carry the result generated by 
 * an external activity invoked by the service
 */
public class ActivityResult {

	private int requestCode;
	private int resultCode;
	private Intent data;
	
	
	public ActivityResult(int requestCode, int resultCode, Intent data) {
		super();
		this.requestCode = requestCode;
		this.resultCode = resultCode;
		this.data = data;
	}


	public int getRequestCode() {
		return requestCode;
	}


	public int getResultCode() {
		return resultCode;
	}


	public Intent getData() {
		return data;
	}
	
	
}
